version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - chmod +x gradlew
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew bootJar
  post_build:
    commands:
      - echo Build completed on `date`
      - echo `ls`
      - echo `ls build`
      - echo `ls build/libs`
artifacts:
  files:
    - build/libs/aws-code-deploy-demo-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
